spring:
  datasource:
    username: root
    password: test1234

email:
  send:
    confirmation: https://mars-demo.progmasters.hu/register-success/

cors-policies: http://54.229.84.224, https://54.229.84.224, http://mars-demo.progmasters.hu, https://mars-demo.progmasters.hu
